#!/usr/bin/env python3
"""Witness for the state and phase scrubber. Fails if a planted secret survives."""

from __future__ import annotations

import json
import shutil
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import scrub_core  # noqa: E402


PLANTED = """product=Swiss Army VPN
password=hunter2-not-real
token=ghp_abcdefghijklmnopqrstuvwxyz123456
github_pat_abcdefghijklmnopqrstuvwxyz123456
-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEA7example
-----END RSA PRIVATE KEY-----
jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0In0.signaturepad
path=C:\\Users\\Justichuu\\AppData\\Roaming\\secret.txt
home=/home/justichuu/.ssh/id_rsa
mail=person@example.com
host=203.0.113.10
I am an AI assistant writing this note.
Generated by GitHub Copilot.
"""


def main() -> int:
    failures = []
    rules = scrub_core.load_rules()
    if not rules.get("offline_only"):
        failures.append("rules must stay offline")

    work = Path(tempfile.mkdtemp(prefix="swiss-army-scrub-"))
    try:
        source = work / "dirty"
        source.mkdir()
        (source / "install-state.txt").write_text(PLANTED, encoding="utf-8")
        output = work / "clean"
        report = scrub_core.scrub(source, output, scan_only=False)
        cleaned = (output / "install-state.txt").read_text(encoding="utf-8")

        forbidden = [
            "hunter2-not-real",
            "ghp_abcdefghijklmnopqrstuvwxyz123456",
            "github_pat_abcdefghijklmnopqrstuvwxyz123456",
            "BEGIN RSA PRIVATE KEY",
            "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
            "C:\\Users\\Justichuu",
            "/home/justichuu",
            "person@example.com",
            "203.0.113.10",
            "I am an AI",
            "GitHub Copilot",
        ]
        for item in forbidden:
            if item.lower() in cleaned.lower():
                failures.append("survived redaction: " + item)

        if report["leftover_secrets"]:
            failures.append("verify reported leftover secrets: " + json.dumps(report["leftover_secrets"]))
        if not report["offline"]:
            failures.append("report must say offline")
        if report["local_witness"] is not None:
            failures.append("this machine should not claim a local witness")
        if "Ask for that witness" not in report["ask_later"]:
            failures.append("missing ask-later note for Justichuu's local witness")

        compiled = scrub_core.compile_rules(rules)
        repo_secrets = []
        for path in scrub_core.walk_sources(ROOT, rules):
            try:
                text = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                continue
            _, findings = scrub_core.classify_and_redact(text, compiled)
            for finding in findings:
                if finding["kind"] == "secret" and finding["id"] in {
                    "github-pat",
                    "github-fine-grained",
                    "pem-private-key",
                    "jwt",
                }:
                    repo_secrets.append(f"{path}: {finding['id']}")
        if repo_secrets:
            failures.append("repo contains live secret material: " + "; ".join(repo_secrets))
    finally:
        shutil.rmtree(work, ignore_errors=True)

    if failures:
        print("STATE PHASE SCRUBBER: FAIL")
        for item in failures:
            print("  " + item)
        return 1

    print("STATE PHASE SCRUBBER: PASS")
    print("  planted secrets removed")
    print("  leftover secret check empty")
    print("  repo has no live tokens or private keys")
    print("  local witness asked later")
    return 0


if __name__ == "__main__":
    sys.exit(main())
