# SPDX-License-Identifier: GPL-3.0-only
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidatePattern('^\d+\.\d+\.\d+$')]
    [string]$Version,

    [Parameter(Mandatory)]
    [string]$DistributionPath,

    [Parameter(Mandatory)]
    [string]$SourcePath,

    [string]$OutputPath = ''
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

function Get-NormalizedFilePath {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Description
    )

    $normalized = [IO.Path]::GetFullPath($Path)
    if (-not (Test-Path -LiteralPath $normalized -PathType Leaf)) {
        throw "$Description is missing: $normalized"
    }
    $item = Get-Item -LiteralPath $normalized -Force
    if (($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) {
        throw "$Description must not be a linked file: $normalized"
    }
    return $normalized
}

function Assert-ReleaseArchiveName {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$PackageKind,
        [Parameter(Mandatory)][string]$ExpectedVersion
    )

    $escapedKind = [regex]::Escape($PackageKind)
    $escapedVersion = [regex]::Escape($ExpectedVersion)
    $pattern = "^Switzerland(?: |\.)VPN(?: |\.)$escapedKind(?: |\.)$escapedVersion\.zip$"
    if ([IO.Path]::GetFileName($Path) -cnotmatch $pattern) {
        throw "$PackageKind ZIP filename does not match version ${ExpectedVersion}: $Path"
    }
}

function Write-Utf8NoBom {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Text
    )

    [IO.File]::WriteAllText($Path, $Text, [Text.UTF8Encoding]::new($false))
}

$repositoryRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..')).TrimEnd('\')
$distribution = Get-NormalizedFilePath -Path $DistributionPath -Description 'Distribution ZIP'
$source = Get-NormalizedFilePath -Path $SourcePath -Description 'Source ZIP'
Assert-ReleaseArchiveName -Path $distribution -PackageKind 'Distribution' -ExpectedVersion $Version
Assert-ReleaseArchiveName -Path $source -PackageKind 'Source' -ExpectedVersion $Version

$distributionDirectory = [IO.Path]::GetDirectoryName($distribution)
$sourceDirectory = [IO.Path]::GetDirectoryName($source)
if (-not [string]::Equals($distributionDirectory, $sourceDirectory, [StringComparison]::OrdinalIgnoreCase)) {
    throw 'The distribution and source ZIPs must be in the same handoff folder.'
}

$OutputPath = if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    Join-Path $distributionDirectory "Verify Switzerland VPN Release $Version.exe"
}
else {
    [IO.Path]::GetFullPath($OutputPath)
}
if (-not [string]::Equals([IO.Path]::GetDirectoryName($OutputPath), $distributionDirectory, [StringComparison]::OrdinalIgnoreCase)) {
    throw 'The verifier must be built beside the two ZIPs it verifies.'
}
$expectedOutputName = "Verify Switzerland VPN Release $Version.exe"
if ([IO.Path]::GetFileName($OutputPath) -cne $expectedOutputName) {
    throw "The verifier output must use the exact filename: $expectedOutputName"
}
if ([string]::Equals($OutputPath, $distribution, [StringComparison]::OrdinalIgnoreCase) -or
    [string]::Equals($OutputPath, $source, [StringComparison]::OrdinalIgnoreCase)) {
    throw 'The verifier output cannot replace either release archive.'
}

$sourceCode = Join-Path $repositoryRoot 'src\SwitzerlandVPN.ReleaseVerifier.cs'
$manifest = Join-Path $repositoryRoot 'src\SwitzerlandVPN.ReleaseVerifier.exe.manifest'
$icon = Join-Path $repositoryRoot 'assets\Switzerland VPN.ico'
$compiler = Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\csc.exe'
foreach ($required in @($sourceCode, $manifest, $icon, $compiler)) {
    if (-not (Test-Path -LiteralPath $required -PathType Leaf)) {
        throw "Required verifier build input is missing: $required"
    }
}

$buildRoot = Join-Path $distributionDirectory ('.verifier-build-' + [guid]::NewGuid().ToString('N'))
$temporaryOutput = Join-Path $distributionDirectory ('.release-verifier-' + [guid]::NewGuid().ToString('N') + '.exe')
New-Item -ItemType Directory -Path $buildRoot | Out-Null
try {
    $distributionHash = (Get-FileHash -LiteralPath $distribution -Algorithm SHA256).Hash
    $sourceHash = (Get-FileHash -LiteralPath $source -Algorithm SHA256).Hash
    $generatedSource = Join-Path $buildRoot 'EmbeddedReleaseManifest.g.cs'
    $escapedVersion = $Version.Replace('"', '\"')
    $generatedText = @"
// Generated by Build-ReleaseVerifier.ps1. Do not commit generated values.
using System.Reflection;

[assembly: AssemblyTitle("Switzerland VPN Release Verifier")]
[assembly: AssemblyDescription("Verifies exact Switzerland VPN distribution and source archives")]
[assembly: AssemblyCompany("Justichuu")]
[assembly: AssemblyProduct("Switzerland VPN Release Verifier")]
[assembly: AssemblyCopyright("Copyright © Justichuu 2026")]
[assembly: AssemblyVersion("$escapedVersion.0")]
[assembly: AssemblyFileVersion("$escapedVersion.0")]

namespace SwitzerlandVPN.ReleaseVerification
{
    internal static class EmbeddedReleaseManifest
    {
        internal const string Version = "$escapedVersion";
        internal const string DistributionSha256 = "$distributionHash";
        internal const string SourceSha256 = "$sourceHash";
    }
}
"@
    Write-Utf8NoBom -Path $generatedSource -Text $generatedText

    & $compiler `
        /nologo `
        /target:winexe `
        /optimize+ `
        /platform:anycpu `
        /warn:4 `
        /warnaserror+ `
        "/win32manifest:$manifest" `
        "/win32icon:$icon" `
        /reference:System.Drawing.dll `
        /reference:System.Security.dll `
        /reference:System.Windows.Forms.dll `
        "/out:$temporaryOutput" `
        $sourceCode `
        $generatedSource
    if ($LASTEXITCODE -ne 0) {
        throw "Release verifier compilation failed with exit code $LASTEXITCODE."
    }

    $expectedFileVersion = $Version + '.0'
    $versionInfo = [Diagnostics.FileVersionInfo]::GetVersionInfo($temporaryOutput)
    if ($versionInfo.FileVersion -ne $expectedFileVersion -or
        $versionInfo.CompanyName -ne 'Justichuu' -or
        $versionInfo.FileDescription -ne 'Switzerland VPN Release Verifier') {
        throw "Release verifier metadata does not match version $expectedFileVersion and publisher Justichuu."
    }

    $verificationProcess = Start-Process -FilePath $temporaryOutput -ArgumentList '--quiet' `
        -WorkingDirectory $distributionDirectory -Wait -PassThru
    if ($verificationProcess.ExitCode -ne 0) {
        throw "The built release verifier rejected its own input archives with exit code $($verificationProcess.ExitCode)."
    }

    if (Test-Path -LiteralPath $OutputPath) {
        Remove-Item -LiteralPath $OutputPath -Force
    }
    Move-Item -LiteralPath $temporaryOutput -Destination $OutputPath

    [pscustomobject]@{
        Version = $Version
        Verifier = $OutputPath
        DistributionSha256 = $distributionHash
        SourceSha256 = $sourceHash
    }
}
finally {
    if (Test-Path -LiteralPath $temporaryOutput) {
        Remove-Item -LiteralPath $temporaryOutput -Force
    }
    if (Test-Path -LiteralPath $buildRoot) {
        Remove-Item -LiteralPath $buildRoot -Recurse -Force
    }
}
